apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
  namespace: chat-dev
  labels:
    app: backend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      env: dev
  template:
    metadata:
      labels:
        app: backend
        env: dev
    spec:
      containers:
        - name: backend
          image: ghcr.io/mdarifahammedreza/simpleChatserver-backend:dev-latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "development"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
