apiVersion: v1
kind: Service
metadata:
  name: backend-dev
  namespace: chat-dev
  labels:
    app: backend
    env: dev
spec:
  type: ClusterIP
  selector:
    app: backend
    env: dev
  ports:
    - port: 5000
      targetPort: 5000
