apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-stage
  namespace: chat-stage
  labels:
    app: backend
    env: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      env: stage
  template:
    metadata:
      labels:
        app: backend
        env: stage
    spec:
      containers:
        - name: backend
          image: ghcr.io/mdarifahammedreza/simpleChatserver-backend:stage-latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
