apiVersion: v1
kind: Service
metadata:
  name: backend-stage
  namespace: chat-stage
  labels:
    app: backend
    env: stage
spec:
  type: ClusterIP
  selector:
    app: backend
    env: stage
  ports:
    - port: 5000
      targetPort: 5000
